-- =====================================================
-- Object Tagging 개요 (Snowflake Data Governance)
--
-- Object Tagging 정의:
--  - Snowflake 내 데이터 오브젝트에 의미나 속성을 부여하는
--    메타데이터 관리 기능
--
-- 적용 대상:
--  - Database, Schema, Table, Column, View
--  - Pipe, Task 등 Snowflake 오브젝트 전반
--
-- 역할 및 활용:
--  - 데이터 거버넌스(Data Governance) 강화를 위한 메타데이터 관리
--  - 데이터 카탈로그(Data Catalog) 구성 및 데이터 탐색성 향상
--  - 민감도, 소유자, 사용 목적 등 속성 정보 표준화
--
-- 본 파일의 목적:
--  - Object Tagging 기능의 구조와 적용 방식을 이해하기 위한 실습
--  - 사용 목적 및 데이터 특성에 따라 사용자 정의 태그를
--    자유롭게 생성·부여하는 것을 전제로 함
--  - 생성된 태그를 Masking Policy 정의·적용 시 연동하여 자동화 기반으로 활용
-- =====================================================

-- Snowflake 오브젝트 태깅(Object Tagging) 생성
CREATE OR REPLACE TAG TAG_SENSITIVITY COMMENT='마스킹 처리 대상';

-- 태그 값 부여
-- ===================================================================
-- 생산 기술팀(HYBRID_MANUFACTURING_CATEGORICAL) 마스킹 처리 대상 태그 부여
-- ===================================================================
ALTER TABLE BRONZE_DB.RAW_CSV.HYBRID_MANUFACTURING_CATEGORICAL
    MODIFY COLUMN MACHINE_ID SET TAG TAG_SENSITIVITY = 'MEDIUM';
    
ALTER TABLE BRONZE_DB.RAW_CSV.HYBRID_MANUFACTURING_CATEGORICAL
    MODIFY COLUMN SCHEDULED_START SET TAG TAG_SENSITIVITY = 'MEDIUM';

ALTER TABLE BRONZE_DB.RAW_CSV.HYBRID_MANUFACTURING_CATEGORICAL
    MODIFY COLUMN SCHEDULED_END SET TAG TAG_SENSITIVITY = 'MEDIUM';

-- ===================================================================
-- 품질 기술팀(MANUFACTURING_DEFECT_DATASET) 마스킹 처리 대상 태그 부여
-- ===================================================================
ALTER TABLE BRONZE_DB.RAW_CSV.MANUFACTURING_DEFECT_DATASET
    MODIFY COLUMN SUPPLIER_QUALITY SET TAG TAG_SENSITIVITY = 'HIGH';
    
ALTER TABLE BRONZE_DB.RAW_CSV.MANUFACTURING_DEFECT_DATASET
    MODIFY COLUMN DEFECT_RATE SET TAG TAG_SENSITIVITY = 'HIGH';
    
ALTER TABLE BRONZE_DB.RAW_CSV.MANUFACTURING_DEFECT_DATASET
    MODIFY COLUMN QUALITY_SCORE SET TAG TAG_SENSITIVITY = 'HIGH';

ALTER TABLE BRONZE_DB.RAW_CSV.MANUFACTURING_DEFECT_DATASET
    MODIFY COLUMN WORKER_PRODUCTIVITY SET TAG TAG_SENSITIVITY = 'HIGH';

ALTER TABLE BRONZE_DB.RAW_CSV.MANUFACTURING_DEFECT_DATASET
    MODIFY COLUMN SAFETY_INCIDENTS SET TAG TAG_SENSITIVITY = 'HIGH';

-- ===================================================================
-- 생산 관리팀(HYBRID_MANUFACTURING_CLEAN) 마스킹 처리 대상 태그 부여
-- ===================================================================
ALTER TABLE SILVER_DB.CLEANED_TRANSFORMED.HYBRID_MANUFACTURING_CLEAN
    MODIFY COLUMN MACHINE_ID SET TAG TAG_SENSITIVITY = 'MEDIUM';
    
ALTER TABLE SILVER_DB.CLEANED_TRANSFORMED.HYBRID_MANUFACTURING_CLEAN
    MODIFY COLUMN SCHEDULED_START_TS SET TAG TAG_SENSITIVITY = 'MEDIUM';

ALTER TABLE SILVER_DB.CLEANED_TRANSFORMED.HYBRID_MANUFACTURING_CLEAN
    MODIFY COLUMN SCHEDULED_END_TS SET TAG TAG_SENSITIVITY = 'MEDIUM';

-- ===================================================================
-- 품질 관리팀(MANUFACTURING_DEFECT_CLEAN) 마스킹 처리 대상 태그 부여
-- ===================================================================
ALTER TABLE SILVER_DB.CLEANED_TRANSFORMED.MANUFACTURING_DEFECT_CLEAN
    MODIFY COLUMN OUTPUT_LEVEL SET TAG TAG_SENSITIVITY = 'HIGH';
    
ALTER TABLE SILVER_DB.CLEANED_TRANSFORMED.MANUFACTURING_DEFECT_CLEAN
    MODIFY COLUMN SUPPLIER_QUALITY_PERCENT SET TAG TAG_SENSITIVITY = 'HIGH';
    
ALTER TABLE SILVER_DB.CLEANED_TRANSFORMED.MANUFACTURING_DEFECT_CLEAN
    MODIFY COLUMN DEFECT_RATE_PERCENT SET TAG TAG_SENSITIVITY = 'HIGH';

ALTER TABLE SILVER_DB.CLEANED_TRANSFORMED.MANUFACTURING_DEFECT_CLEAN
    MODIFY COLUMN QUALITY_SCORE_PERCENT SET TAG TAG_SENSITIVITY = 'HIGH';

ALTER TABLE SILVER_DB.CLEANED_TRANSFORMED.MANUFACTURING_DEFECT_CLEAN
    MODIFY COLUMN WORKER_PRODUCTIVITY_PERCENT SET TAG TAG_SENSITIVITY = 'HIGH';

ALTER TABLE SILVER_DB.CLEANED_TRANSFORMED.MANUFACTURING_DEFECT_CLEAN
    MODIFY COLUMN SAFETY_INCIDENT_COUNT SET TAG TAG_SENSITIVITY = 'HIGH';

