-- =====================================================
-- Stream + Task 기반 CDC(증분 반영) 설계 개요
--
-- Stream:
--  - 테이블에 발생한 INSERT / UPDATE / DELETE 변경 내역만 기록하는 객체
--  - 전체 데이터를 다시 조회하지 않고
--    변경 사항만 감지하는 "변경 감지 센서" 역할
--
-- Task:
--  - 지정된 주기(SCHEDULE)에 따라 SQL을 자동 실행하는 Snowflake 스케줄러
--  - Stream에 기록된 변경 데이터를 주기적으로 처리
--
-- Stream + Task 조합 목적:
--  - Stream으로 데이터 변경을 감지하고
--  - Task를 통해 변경분만 증분 반영(CDC) 처리
--  - 대량 데이터 재처리 없이 효율적인 데이터 파이프라인 구성
--
-- 적용 효과:
--  - 증분 적재를 통한 처리 성능 향상
--  - 데이터 최신성 확보
-- =====================================================

-- Stream 생성 대상이 되는 Bronze 테이블의 Database / Schema 설정
USE BRONZE_DB.RAW_CSV;

-- Stream + task(Silver 진행)
-- =====================
-- HYBRID_MANUFACTURING
-- ======================
-- Stream 생성
CREATE OR REPLACE STREAM HYBRID_MANUFACTURING_STREAM
ON TABLE BRONZE_DB.RAW_CSV.HYBRID_MANUFACTURING_CATEGORICAL;

-- Task 생성
CREATE OR REPLACE TASK HYBRID_MANUFACTURING_TASK
WAREHOUSE = COMPUTE_WH
-- 변경사항을 빠르게 반영하기 위해 1분 주기 설정(운영 시 주기 조정)
SCHEDULE = '1 MINUTE'
AS
MERGE INTO SILVER_DB.CLEANED_TRANSFORMED.HYBRID_MANUFACTURING_CLEAN T
USING (
    SELECT *
    FROM HYBRID_MANUFACTURING_STREAM
    WHERE Job_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY Job_ID
        ORDER BY METADATA$ROW_ID DESC
    ) = 1
) S
ON T.Job_ID = S.Job_ID
-- Job_ID 기준 매칭 시, 기존 행의 변경된 컬럼 업데이트
WHEN MATCHED AND S.METADATA$ACTION = 'UPDATE'
THEN UPDATE SET
    T.MACHINE_ID = S.MACHINE_ID,
    T.OPERATION_TYPE = S.OPERATION_TYPE,
    T.MATERIAL_USED = S.MATERIAL_USED,
    T.PROCESSING_TIME = S.PROCESSING_TIME,
    T.ENERGY_CONSUMPTION = S.ENERGY_CONSUMPTION,
    T.MACHINE_AVAILABILITY = S.MACHINE_AVAILABILITY,
    T.SCHEDULED_START_TS = S.SCHEDULED_START,
    T.SCHEDULED_END_TS = S.SCHEDULED_END,
    T.ACTUAL_START_TS = S.ACTUAL_START,
    T.ACTUAL_END_TS = S.ACTUAL_END,
    T.JOB_STATUS = S.JOB_STATUS,
    T.OPTIMIZATION_CATEGORY = S.OPTIMIZATION_CATEGORY
-- Job_ID 기준 매칭되지 않은 경우, 신규 데이터로 판단하여 행 삽입
WHEN NOT MATCHED AND S.METADATA$ACTION = 'INSERT'
THEN INSERT (
    JOB_ID,               
    MACHINE_ID,           
    OPERATION_TYPE,       
    MATERIAL_USED,        
    PROCESSING_TIME,      
    ENERGY_CONSUMPTION,   
    MACHINE_AVAILABILITY, 
    SCHEDULED_START_TS,   
    SCHEDULED_END_TS,     
    ACTUAL_START_TS,      
    ACTUAL_END_TS,        
    JOB_STATUS,           
    OPTIMIZATION_CATEGORY
    
)
VALUES (
    S.JOB_ID,
    S.MACHINE_ID,
    S.OPERATION_TYPE,
    S.MATERIAL_USED,
    S.PROCESSING_TIME,
    S.ENERGY_CONSUMPTION,
    S.MACHINE_AVAILABILITY,
    S.SCHEDULED_START,
    S.SCHEDULED_END,
    S.ACTUAL_START,
    S.ACTUAL_END,
    S.JOB_STATUS,
    S.OPTIMIZATION_CATEGORY
);

-- Task 활성화 (기본값은 비활성화)
ALTER TASK HYBRID_MANUFACTURING_TASK RESUME;
ALTER TASK HYBRID_MANUFACTURING_TASK SUSPEND;

-- Stream 변경 내역 확인 (CDC 이벤트 확인)
SELECT
    METADATA$ACTION,
    METADATA$ISUPDATE,
    METADATA$ROW_ID
FROM BRONZE_DB.RAW_CSV.HYBRID_MANUFACTURING_STREAM;

-- Stream + task(Silver 진행)
-- =====================
-- MANUFACTURING_DEFECT
-- ======================
-- Stream 생성
CREATE OR REPLACE STREAM MANUFACTURING_DEFECT_STREAM
ON TABLE BRONZE_DB.RAW_CSV.MANUFACTURING_DEFECT_DATASET;

-- Task 생성
CREATE OR REPLACE TASK MANUFACTURING_DEFECT_TASK
WAREHOUSE = COMPUTE_WH
-- 변경사항을 빠르게 반영하기 위해 1분 주기 설정(운영 시 주기 조정)
SCHEDULE = '1 MINUTE'
AS
MERGE INTO SILVER_DB.CLEANED_TRANSFORMED.MANUFACTURING_DEFECT_CLEAN T
USING (
    SELECT *
    FROM MANUFACTURING_DEFECT_STREAM
    WHERE PRODUCTION_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY PRODUCTION_ID
        ORDER BY METADATA$ROW_ID DESC
    ) = 1
) S
ON T.PRODUCTION_ID = S.PRODUCTION_ID

-- PRODUCTION_ID 기준 매칭 시, 기존 행의 변경된 컬럼 업데이트
WHEN MATCHED AND S.METADATA$ACTION = 'UPDATE'
THEN UPDATE SET
    -- Bronze에는 존재하지 않는 파생 컬럼으로,
    -- Silver 단계에서 정의한 생산량 기준으로 재계산하여 OUTPUT_LEVEL 반영
    T.OUTPUT_LEVEL =
        CASE 
            WHEN S.PRODUCTION_VOLUME < 100 THEN 'LOW'
            WHEN S.PRODUCTION_VOLUME < 300 THEN 'MID_LOW'
            WHEN S.PRODUCTION_VOLUME < 600 THEN 'MID'
            WHEN S.PRODUCTION_VOLUME < 900 THEN 'MID_HIGH'
            WHEN S.PRODUCTION_VOLUME >= 900 THEN 'HIGH'
            ELSE NULL
        END,
    T.PRODUCTION_VOLUME = S.PRODUCTION_VOLUME,
    T.PRODUCTION_COST_USD = S.PRODUCTION_COST,
    T.SUPPLIER_QUALITY_PERCENT = S.SUPPLIER_QUALITY,
    T.DELIVERY_DELAY_DAYS = S.DELIVERY_DELAY,
    T.DEFECT_RATE_PERCENT = S.DEFECT_RATE,
    T.QUALITY_SCORE_PERCENT = S.QUALITY_SCORE,
    T.MAINTENANCE_HOURS = S.MAINTENANCE_HOURS,
    T.DOWNTIME_PERCENT = S.DOWNTIME_PERCENTAGE,
    T.INVENTORY_TURNOVER_RATIO = S.INVENTORY_TURNOVER,
    T.STOCKOUT_RATE_PERCENT = S.STOCKOUT_RATE,
    T.WORKER_PRODUCTIVITY_PERCENT = S.STOCKOUT_RATE,
    T.SAFETY_INCIDENT_COUNT = S.SAFETY_INCIDENTS,
    T.ENERGY_CONSUMPTION_KWH = S.ENERGY_CONSUMPTION,
    T.ENERGY_EFFICIENCY_RATIO = S.ENERGY_EFFICIENCY,
    T.ADDITIVE_PROCESS_HOURS = S.ADDITIVE_PROCESS_TIME,
    T.ADDITIVE_MATERIAL_COST_USD = S.ADDITIVE_MATERIAL_COST,
    T.DEFECT_STATUS =
        CASE
            WHEN S.DEFECT_STATUS IN (FALSE, 0) THEN '낮음'
            WHEN S.DEFECT_STATUS IN (TRUE, 1)  THEN '높음'
            ELSE 'Undefined'
        END
-- PRODUCTION_ID 기준 매칭되지 않은 경우, 신규 데이터로 판단하여 행 삽입
WHEN NOT MATCHED AND S.METADATA$ACTION = 'INSERT'
THEN INSERT (
    PRODUCTION_ID,
    OUTPUT_LEVEL,
    PRODUCTION_VOLUME,
    PRODUCTION_COST_USD, 
    SUPPLIER_QUALITY_PERCENT,
    DELIVERY_DELAY_DAYS,
    DEFECT_RATE_PERCENT,
    QUALITY_SCORE_PERCENT,
    MAINTENANCE_HOURS,
    DOWNTIME_PERCENT,
    INVENTORY_TURNOVER_RATIO,
    STOCKOUT_RATE_PERCENT,
    WORKER_PRODUCTIVITY_PERCENT,
    SAFETY_INCIDENT_COUNT, 
    ENERGY_CONSUMPTION_KWH, 
    ENERGY_EFFICIENCY_RATIO, 
    ADDITIVE_PROCESS_HOURS,
    ADDITIVE_MATERIAL_COST_USD,
    DEFECT_STATUS
    
)
VALUES (
    S.PRODUCTION_ID,
    CASE 
        WHEN S.PRODUCTION_VOLUME < 100 THEN 'LOW'
        WHEN S.PRODUCTION_VOLUME < 300 THEN 'MID_LOW'
        WHEN S.PRODUCTION_VOLUME < 600 THEN 'MID'
        WHEN S.PRODUCTION_VOLUME < 900 THEN 'MID_HIGH'
        WHEN S.PRODUCTION_VOLUME >= 900 THEN 'HIGH'
        ELSE NULL
    END,
    S.PRODUCTION_VOLUME,
    S.PRODUCTION_COST,
    S.SUPPLIER_QUALITY,
    S.DELIVERY_DELAY,
    S.DEFECT_RATE,
    S.QUALITY_SCORE,
    S.MAINTENANCE_HOURS,
    S.DOWNTIME_PERCENTAGE,
    S.INVENTORY_TURNOVER,
    S.STOCKOUT_RATE,
    S.WORKER_PRODUCTIVITY,
    S.SAFETY_INCIDENTS,
    S.ENERGY_CONSUMPTION,
    S.ENERGY_EFFICIENCY,
    S.ADDITIVE_PROCESS_TIME,
    S.ADDITIVE_MATERIAL_COST,
    CASE
        WHEN S.DEFECT_STATUS IN (FALSE, 0) THEN '낮음'
        WHEN S.DEFECT_STATUS IN (TRUE, 1)  THEN '높음'
        ELSE 'Undefined'
    END
);

-- Task 활성화 (기본값은 비활성화)
ALTER TASK MANUFACTURING_DEFECT_TASK RESUME;
ALTER TASK MANUFACTURING_DEFECT_TASK SUSPEND;

-- Stream 변경 내역 확인 (CDC 이벤트 확인)
SELECT
    METADATA$ACTION,
    METADATA$ISUPDATE,
    METADATA$ROW_ID
FROM BRONZE_DB.RAW_CSV.MANUFACTURING_DEFECT_STREAM;